[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sol_version = "0.8.20" 
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
